# run: conda env create --file environment.yml
name: ttrecipes
dependencies:
- python>=3.3
- pip
- numpy
- scipy
- six
- cython
- matplotlib
#- gcc             ## Optional install of gfortran compiler (required for ttpy) with conda
#- pip:            ## Optional install of ttpy with conda 
#  - ttpy
